apiVersion: v1
kind: Service
metadata:
  labels:
    service-label-key: lb-ng-gke
  name: ng-gke-loadbalancer
spec:
  type: LoadBalancer
  ports:
    - name: ng-gke-loadbalancer
      port: 80
      protocol: TCP
  selector:
      app: ng-gke